# Generated by Django 4.2.5 on 2026-03-25 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(help_text="Введите username, не длиннее 50 символов. Использовать нужно английский алфавит, разделять фразы нужно символом '-'", unique=True, verbose_name='Имя аккаунта')),
                ('email', models.EmailField(help_text='Адрес почты в формате *@*.*', max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('first_name', models.CharField(blank=True, help_text='Ограничение - не более 100 символов', max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Ограничение - не более 100 символов', max_length=100, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, help_text='Ограничение - не более 100 символов', max_length=100, null=True, verbose_name='Отчество')),
                ('gender', models.CharField(blank=True, choices=[('м', 'мужской'), ('ж', 'женский')], help_text='Выберите пол', max_length=1, null=True, verbose_name='Пол')),
                ('self_esteem', models.DecimalField(blank=True, decimal_places=1, help_text="Введите уровень вашей самооценки, только честно! Градация от 0 до 5, где 0 - 'я молодец', 5 - 'я умница'", max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0, 'Диапазон [0.0, 5.0]'), django.core.validators.MaxValueValidator(5, 'Диапазон [0.0, 5.0]')], verbose_name='Уровень самооценки')),
                ('phone_number', models.CharField(blank=True, help_text="Введите номер телефона через '+7' без пробелов в формате +79123456789 ", max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть формата: '+79123456789'.", regex='^\\+79\\d{9}$')], verbose_name='Номер телефона')),
                ('city', models.CharField(blank=True, help_text='Введите название города', max_length=100, null=True, verbose_name='Город')),
                ('bio', models.TextField(blank=True, help_text='Напишите здесь о том, почему Вы так хороши', null=True, verbose_name='Биография')),
                ('age', models.IntegerField(editable=False, null=True)),
                ('date_birth', models.DateField(blank=True, help_text='Посланцев из будущего не регистрируем!', null=True, verbose_name='Дата рождения')),
                ('status_rule', models.BooleanField(help_text='А ты их читал или как обычно просто галочку поставил?', verbose_name='Согласие с правилами')),
                ('image', models.ImageField(blank=True, help_text='Фото в профиль, можно не своё! Ну или хоть какое-то. Ладно можно без фото', null=True, upload_to='foto_profile', verbose_name='Картинка профиля')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
    ]
